models:
  gpt-4o:
    max_number_of_tools: 128
    use_system_message: true
    system_message_type: 'system'
    documents_chunk_size: 60000
    documents_chunk_overlap: 0
    documents_context_window: 70000
    tokenizer_model_name: 'gpt-4o'
    supports_structured_output: true
    structured_output_supports_temperature: true

  o1-preview:
    max_number_of_tools: 0
    use_system_message: false
    documents_chunk_size: 60000
    documents_chunk_overlap: 0
    documents_context_window: 70000
    tokenizer_model_name: 'gpt-4'
    supports_structured_output: false

  o1-mini:
    max_number_of_tools: 0
    use_system_message: false
    documents_chunk_size: 60000
    documents_chunk_overlap: 0
    documents_context_window: 70000
    tokenizer_model_name: 'gpt-4'
    supports_structured_output: false

  gemini-2.0-flash-thinking-exp:
    max_number_of_tools: 0
    use_system_message: true
    system_message_type: 'system'
    documents_chunk_size: 700000
    documents_chunk_overlap: 0
    documents_context_window: 800000
    tokenizer_model_name: 'gpt2'
    supports_structured_output: false

  gemini-2.0-pro-exp:
    max_number_of_tools: 0
    use_system_message: true
    system_message_type: 'system'
    documents_chunk_size: 60000
    documents_chunk_overlap: 0
    documents_context_window: 71000
    tokenizer_model_name: 'gpt2'
    supports_structured_output: false

  deepseek/deepseek-r1:
    max_number_of_tools: 0
    use_system_message: true
    system_message_type: 'system'
    documents_chunk_size: 55000
    documents_chunk_overlap: 0
    documents_context_window: 60000
    tokenizer_model_name: 'gpt2'
    supports_structured_output: false


  o1:
    max_number_of_tools: 0
    use_system_message: true
    system_message_type: 'developer'
    documents_chunk_size: 90000
    documents_chunk_overlap: 0
    documents_context_window: 100000
    tokenizer_model_name: 'gpt-4'
    supports_structured_output: false
    reasoning_effort: 'high'


  openai/o1:
    max_number_of_tools: 0
    use_system_message: true
    system_message_type: 'developer'
    documents_chunk_size: 90000
    documents_chunk_overlap: 0
    documents_context_window: 100000
    tokenizer_model_name: 'gpt-4'
    supports_structured_output: false
    reasoning_effort: 'high'


  o3-mini:
    max_number_of_tools: 0
    use_system_message: true
    system_message_type: 'developer'
    documents_chunk_size: 90000
    documents_chunk_overlap: 0
    documents_context_window: 100000
    tokenizer_model_name: 'gpt-4'
    supports_structured_output: false
    reasoning_effort: 'high'

  anthropic/claude-3.7-sonnet:
    max_number_of_tools: 0
    use_system_message: true
    system_message_type: 'system'
    documents_chunk_size: 90000
    documents_chunk_overlap: 0
    documents_context_window: 100000
    tokenizer_model_name: 'gpt2'
    supports_structured_output: false

  anthropic/claude-3.7-sonnet\:thinking:
    max_number_of_tools: 0
    use_system_message: true
    system_message_type: 'system'
    documents_chunk_size: 90000
    documents_chunk_overlap: 0
    documents_context_window: 100000
    tokenizer_model_name: 'gpt2'
    supports_structured_output: false

  gpt-4.5-preview:
    max_number_of_tools: 0
    use_system_message: true
    system_message_type: 'system'
    documents_chunk_size: 90000
    documents_chunk_overlap: 0
    documents_context_window: 100000
    tokenizer_model_name: 'gpt-4'
    supports_structured_output: false
    max_tokens: 16384

  claude-3-7-sonnet-latest:
    max_number_of_tools: 0
    use_system_message: true
    system_message_type: 'system'
    documents_chunk_size: 90000
    documents_chunk_overlap: 0
    documents_context_window: 100000
    tokenizer_model_name: 'gpt2'
    supports_structured_output: false
    thinking: true
    thinking_budget_tokens: 32000
    max_tokens: 64000

default:
  max_number_of_tools: 1000
  use_system_message: true
  system_message_type: 'system'
  documents_chunk_size: 60000
  documents_chunk_overlap: 0
  documents_context_window: 70000
  tokenizer_model_name: 'gpt2'
  supports_structured_output: false
  max_tokens: 100000
